import 'package:education_admin_portal/presentation/common_widgets/input_field/common_mobile_field.dart';
import 'package:flutter/material.dart';
import 'package:gap/gap.dart';
import 'package:get/get.dart';

import '../../../../core/constants/app_assets.dart';
import '../../../../core/constants/app_colors.dart';
import '../../../../core/constants/app_strings.dart';
import '../../../../utils/extensions/responsive.dart';
import '../../../app/theme_controller.dart';
import '../../../common_widgets/common_text_view/auth_common_text.dart';
import '../../../common_widgets/view_common_widget/common_app_bar.dart';
import '../../../common_widgets/view_common_widget/common_card_decoration.dart';
import '../../../common_widgets/view_common_widget/common_circular_loader.dart';
import '../../../common_widgets/widgets/button.dart';
import '../../../common_widgets/widgets/image.dart';
import '../../../common_widgets/widgets/validations.dart';
import 'controller/forgot_password_controller.dart';
part 'forgot_password_view.dart';